### PR TITLE
fix: increase blowing in on boarding screen 

### LINKED ISSUE #697: Increase Glow in onBoarding screen

### LINKED ISSUE #698: Make the image of onBoarding in the center of big device

### PR DESCRIPTION
**Pull request by Hasa9nAli**
fix bluring issue and image size

### CODE REVIEW

File: ui/src/main/java/com/baghdad/ui/feature/onBoarding/component/OnBoardingHorizontalPagerContent.kt [hunk 1]
```diff
@@ -153,7 +146,7 @@ private fun TextSlidingAnimationVisibility(
 
 @SuppressLint("ConfigurationScreenWidthHeight")
 @Composable
-private fun isTablet(): Boolean {
```
Comment (Farah315) [inline ui/src/main/java/com/baghdad/ui/feature/onBoarding/component/OnBoardingHorizontalPagerContent.kt:156]: i have a question. is it normal to check if it is a tablet or not?for example, tablets come in different sizes, even phones. is there anything we can do without making a custom for each type of device, because it doesn’t seem logical to me?

Comment (Farah315) [inline ui/src/main/java/com/baghdad/ui/feature/onBoarding/component/OnBoardingHorizontalPagerContent.kt:156]: why did u delete private cuz i don't see u use it in anther place?

**Review by Farah315 — COMMENTED** [review]
great job just check the comment

**Review by fatmahgazy — DISMISSED** [review]
looks good to me

**Review by MahmoodTarek — DISMISSED** [review]
Great Work

**Review by omer1998 — APPROVED** [review]

File: ui/src/main/java/com/baghdad/ui/feature/onBoarding/component/OnBoardingHorizontalPagerContent.kt [hunk 2]
```diff
@@ -139,21 +132,23 @@ private fun TextSlidingAnimationVisibility(
...
+            modifier = Modifier.padding(top = 4.dp, start = 8.dp, end = 8.dp),
             textAlign = TextAlign.Center,
         )
     }
 }
 
 @SuppressLint("ConfigurationScreenWidthHeight")
 @Composable
-private fun isTablet(): Boolean {
+fun isTablet(): Boolean {
```
Comment (abdulazizacc) [inline ui/src/main/java/com/baghdad/ui/feature/onBoarding/component/OnBoardingHorizontalPagerContent.kt:151]: nice way of checking the size

**Review by abdulazizacc — APPROVED** [review]
Well done hasan

**Review by Arzo-zi — APPROVED** [review]

**Review by MahmoodTarek — APPROVED** [review]
