### PR TITLE
Fix/#919 snackbar issues

### LINKED ISSUE #919: Fix snackbar issues

### PR DESCRIPTION
**Pull request by Malak187**
- Fix some of snackbar and retry issues in continue watching, top rating and search screen
- Removed the save icon for TV shows in the recently viewed section

### CODE REVIEW

**Review by MuhammedEdrees — DISMISSED** [review]

**Review by MuhammedEdrees — APPROVED** [review]

File: ui/src/main/java/com/baghdad/ui/feature/actorDetails/ActorDetailsScreen.kt [hunk 1]
```diff
@@ -231,7 +231,7 @@ private fun ActorDetailsContent(
                         title = stringResource(R.string.top_tv_shows_picks),
                         items = uiState.topTvShowsPicks,
                         imageUrl = { it.posterPictureURL },
-                        isSaveVisible = false,
+                        isSaveVisible = { false },
```
Comment (abdulazizacc) [inline ui/src/main/java/com/baghdad/ui/feature/actorDetails/ActorDetailsScreen.kt:234]: what did this change

**Review by abdulazizacc — APPROVED** [review]

File: viewmodel/src/main/java/com/baghdad/viewmodel/continueWatching/ContinueWatchingViewModel.kt [hunk 2]
```diff
@@ -252,6 +252,7 @@ class ContinueWatchingViewModel @Inject constructor(
         }
         getGenres()
         getMedia(genreId)
+        getUserSavedLists()
```
Comment (omer1998) [inline viewmodel/src/main/java/com/baghdad/viewmodel/continueWatching/ContinueWatchingViewModel.kt:255]: why did get user saved list every time when the selected tab change ?

**Review by omer1998 — COMMENTED** [review]
good job malak

File: ui/src/main/java/com/baghdad/ui/feature/actorDetails/ActorDetailsScreen.kt (hunk 1 above)
Comment (Malak187) [reply ui/src/main/java/com/baghdad/ui/feature/actorDetails/ActorDetailsScreen.kt:234]: we converted the parameter to be lambda function to work correctly with the generic function

File: viewmodel/src/main/java/com/baghdad/viewmodel/continueWatching/ContinueWatchingViewModel.kt (hunk 2 above)
Comment (Malak187) [reply viewmodel/src/main/java/com/baghdad/viewmodel/continueWatching/ContinueWatchingViewModel.kt:255]: because without it, the no internet connection snackbar disappears after clicking retry once, even if the device is still offline

**Review by karrar-abbas — APPROVED** [review]
