### PR TITLE
Fix/#621 handle empty api data in the movie details, and TV show details screens

### LINKED ISSUE #621: Handle empty API data by showing the movie poster instead of a placeholder in the movie details, and TV show details screens

### PR DESCRIPTION
**Pull request by fatmahgazy**
- **Handle empty API data by showing the movie poster instead of a placeholder in the movie details, and TV show details screens**
 
Movie: 
Screenshot_٢٠٢٥-٠٨-٠٣-١٩-٣٠-٤٥-٠٢٧_com miui gallery

Tv show:
Screenshot_٢٠٢٥-٠٨-٠٣-١٩-٣٣-٤٢-٩٤٦_com baghdad novix

### CODE REVIEW

File: ui/src/main/java/com/baghdad/ui/feature/movieDetails/component/MovieHeaderWithDetailsCard.kt [hunk 1]
```diff
@@ -26,25 +26,31 @@ import com.baghdad.viewmodel.movieDetails.formatDuration
...
     modifier: Modifier = Modifier
 ) {
-    val pagerState = rememberPagerState(pageCount = { state.movieImages.size })
+    val pagerState = rememberPagerState(pageCount = { uiState.movieImages.size })
+
+    val singlePagerState = rememberPagerState(pageCount = { 1 } )
+
+    val images = if (uiState.movieImages.isEmpty()) listOf(uiState.posterImageURL) else { uiState.movieImages }
+    val aspectRatio = if (uiState.movieImages.isNotEmpty()) { 1.778f } else { 1.2f }
+    val currentPagerState = if (uiState.movieImages.isEmpty()){ singlePagerState } else { pagerState }
```
Comment (Malak187) [inline ui/src/main/java/com/baghdad/ui/feature/movieDetails/component/MovieHeaderWithDetailsCard.kt]: Instead of declaring two pager states for poster and backdrops. You can follow the following approach for better readability and writability:

    val images = if (uiState.movieImages.isEmpty()) listOf(uiState.posterImageURL) else { uiState.movieImages }

    val pagerState = rememberPagerState(pageCount = { images.size })
    
 You can use this in both movie and tvshow screens

**Review by Malak187 — COMMENTED** [review]
Well done Fatma

**Review by omer1998 — DISMISSED** [review]
great work fatma, looks good to me

**Review by MuhammedEdrees — DISMISSED** [review]
Well done, Fatma. Just double check with hamsa if this is ok since we are changing the design.

**Review by Hasa9nAli — DISMISSED** [review]

**Review by Hasa9nAli — DISMISSED** [review]

**Review by Arzo-zi — DISMISSED** [review]
well done

**Review by omer1998 — APPROVED** [review]

**Review by ABDULLAHHG — APPROVED** [review]

**Review by Farah315 — APPROVED** [review]
