### PR TITLE
Fix/#844 actor card clipping is incorrect

### LINKED ISSUE #844: Actor card clipping is incorrect ✔
before
Image

### PR DESCRIPTION
**Pull request by Farah315**
What was done in this pr

- [x] fix actor card clipping 
- [x] remove save icon from episode
- [x] remove private fun in authentication
- [x]  remove private fun in movie
- [x] fix web view screen
WhatsApp Image 2025-08-15 at 23 48 01_af4b785c

### CODE REVIEW

File: ui/src/main/java/com/baghdad/ui/feature/component/ActorCard.kt [hunk 1]
```diff
@@ -63,14 +63,15 @@ fun ActorCard(
...
                 .threeSidedBorder(
                     width = 1.dp,
                     color = Theme.color.stroke,
                     cornerRadius = 12.dp,
                     isRTL = isRTL
                 )
-                .clip(RoundedCornerShape(12.dp))
-                .height(55.dp)
+                .background(Theme.color.surface)
                 .padding(horizontal = 8.dp)
```
Comment (Malak187) [inline ui/src/main/java/com/baghdad/ui/feature/component/ActorCard.kt]: are you sure about the arrangement of the modifiers functions here? because i think they are hiding the three sided border, in the description of this pr, I can't see the borders so please check it again

Comment (Farah315) [reply ui/src/main/java/com/baghdad/ui/feature/component/ActorCard.kt]: @Malak187 3ash ya maloka i fix it 
WhatsApp Image 2025-08-16 at 10 17 50_3032e2f8

**Review by MuhammedEdrees — CHANGES_REQUESTED** [review]
Great work, Farah. Please merge develop into this branch to get the latest CI changes.

**Review by Malak187 — APPROVED** [review]

**Review by MuhammedEdrees — APPROVED** [review]
Well done 👏👏👏👏👏👏👏👏👏

**Review by Arzo-zi — APPROVED** [review]
