### PR TITLE
Fix/#917-error-messages-in-login

### LINKED ISSUE #917: Fix error messages in login screen

### PR DESCRIPTION
**Pull request by FaresM0hamed**
Fix error messages in login screen

### CODE REVIEW

File: remote_datasource/src/main/java/com/baghdad/remoteDataSource/util/HandleRequest.kt [hunk 1]
```diff
@@ -13,44 +14,66 @@ import io.ktor.utils.io.errors.IOException
...
         throw mapToNetworkException(e)
     }
+
+    return when {
+        response.isSuccessful -> {
+            try {
+                response.body() ?: throw NullPointerException("Response body is null")
+
+            } catch (e: Exception) {
+                Log.e("NetworkError", "Error parsing response: ${e.message}", e)
```
Comment (abdulazizacc) [inline remote_datasource/src/main/java/com/baghdad/remoteDataSource/util/HandleRequest.kt:38]: delete the logs

**Review by abdulazizacc — APPROVED** [review]

**Review by MuhammedEdrees — APPROVED** [review]

**Review by omer1998 — COMMENTED** [review]
it seems that you're working on the previous implementation of "handleRequest" function
the newer one is much cleaner and readable
if you aware of this, why did you return the implementation to the previous one 
and all you do is trying to catch another exception ?

**Review by Malak187 — APPROVED** [review]

**Review by karrar-abbas — APPROVED** [review]

**Review by Farah315 — APPROVED** [review]

**Review by MahmoodTarek — APPROVED** [review]
