### PR TITLE
Fix/#831 item saved successfully snackbar message not visible in home screen

### LINKED ISSUE #831: Item saved successfully snackbar doesn't appear in home screen

### PR DESCRIPTION
**Pull request by MuhammedEdrees**
### PR Content:
- Fixed a bug where adding/removing movies to saved lists didn't display snack bar message

### CODE REVIEW

File: viewmodel/src/main/java/com/baghdad/viewmodel/home/HomeViewModel.kt [hunk 1]
```diff
@@ -72,14 +61,23 @@ class HomeViewModel
...
-        updateState {
-            it.copy(
-                language = newLanguage,
-            )
+        private fun onGetLanguageChangeSuccess(newLanguage: String) {
+            updateState {
+                it.copy(
+                    language = newLanguage,
+                )
+            }
```
Comment (omer1998) [inline viewmodel/src/main/java/com/baghdad/viewmodel/home/HomeViewModel.kt]: i think we need to remove the language state and also remove this code related to updating it state, no need of it

File: viewmodel/src/main/java/com/baghdad/viewmodel/home/HomeViewModel.kt [hunk 2]
```diff
@@ -269,7 +267,6 @@ class HomeViewModel
         }
 
         private fun onGetUpcomingSuccess(movies: List<SavedMovie>) {
-            hideSnackBar()
```
Comment (omer1998) [inline viewmodel/src/main/java/com/baghdad/viewmodel/home/HomeViewModel.kt:272]: is this the reason for this issue ?

**Review by omer1998 — DISMISSED** [review]
great work muhammed, also the format of the code it looks strange at some points

**Review by MahmoodTarek — DISMISSED** [review]
Great work

File: viewmodel/src/main/java/com/baghdad/viewmodel/home/HomeViewModel.kt (hunk 1 above)
Comment (MuhammedEdrees) [reply viewmodel/src/main/java/com/baghdad/viewmodel/home/HomeViewModel.kt]: hmm makes sense

**Review by abdulazizacc — DISMISSED** [review]

File: viewmodel/src/main/java/com/baghdad/viewmodel/home/HomeViewModel.kt (hunk 2 above)
Comment (MuhammedEdrees) [reply viewmodel/src/main/java/com/baghdad/viewmodel/home/HomeViewModel.kt:272]: This is related to the original issue i was fixing. The snackbar was being hidden on each data reload and data is reload after each save so the snackbar was being hidden immediately after it's shown.

**Review by abdulazizacc — APPROVED** [review]

**Review by omer1998 — APPROVED** [review]

**Review by fatmahgazy — APPROVED** [review]

**Review by FaresM0hamed — APPROVED** [review]
image
