### PR TITLE
Fix: fix button state when it's loading

### LINKED ISSUE #444: When button state is loading, it shouldn't perform any actions

### PR DESCRIPTION
**Pull request by Farah315**
when button state is loading i disable it so we can make sure the user is not click on it

### CODE REVIEW

File: design_system/src/main/java/com/baghdad/design_system/component/button/TextButton.kt [hunk 1]
```diff
@@ -34,7 +34,9 @@ fun TextButton(
     )
     Row(
         modifier = modifier.clickable(enabled = isEnabled) {
-            onClick()
+
+            if (!isLoading) onClick()
```
Comment (MahmoodTarek) [inline design_system/src/main/java/com/baghdad/design_system/component/button/TextButton.kt]: I think the spacing here is a bit too much.  
Maybe we can reduce it to make the code cleaner.

**Review by MahmoodTarek — DISMISSED** [review]
Great work Farah

**Review by ABDULLAHHG — DISMISSED** [review]

**Review by fatmahgazy — DISMISSED** [review]
Good job Farah 👏

**Review by FaresM0hamed — APPROVED** [review]

**Review by Malak187 — APPROVED** [review]

**Review by MuhammedEdrees — APPROVED** [review]
