### PR TITLE
fix/#839-home-upcoming-genres-background-color

### LINKED ISSUE #839: Fix home upcoming genres background color

### PR DESCRIPTION
**Pull request by fatmahgazy**
- **home upcoming genres background color**

- **fix home background top bar the same in figma** 

- **remove geners  loading in upcoming section and delete it from home view model**

### CODE REVIEW

**Review by Malak187 — CHANGES_REQUESTED** [review]
Good work Fatma but you cancelled the loading behavior when switching between genre tabs in the upcoming section. Please try to fix it, you can separate the loading of the upcoming section header and the content itself as a solution.

File: ui/src/main/java/com/baghdad/ui/feature/home/component/UpcomingSection.kt [hunk 1]
```diff
@@ -121,67 +121,71 @@ private fun LazyGridScope.upcomingSectionHeader(
 }
 
 fun LazyGridScope.upcomingSectionLoading(
+    isLoading: Boolean,
```
Comment (MuhammedEdrees) [inline ui/src/main/java/com/baghdad/ui/feature/home/component/UpcomingSection.kt]: If this section is for loading content why do we need isLoading parameter. It's always passed as true aswell.

File: ui/src/main/java/com/baghdad/ui/feature/home/component/UpcomingSection.kt [hunk 2]
```diff
@@ -121,67 +121,71 @@ private fun LazyGridScope.upcomingSectionHeader(
...
+    selectedGenreId: Long?,
+    genres: List<GenreUiState>,
+    onGenreSelected: (GenreUiState?) -> Unit,
     upcomingItems: List<UpcomingItemUiState>,
+    onUpcomingItemClicked: (UpcomingItemUiState) -> Unit,
+    onUpcomingItemSaveClicked: (UpcomingItemUiState) -> Unit,
```
Comment (MuhammedEdrees) [inline ui/src/main/java/com/baghdad/ui/feature/home/component/UpcomingSection.kt]: Most of these parameters are unnecessary since this is only loading content.

File: ui/src/main/java/com/baghdad/ui/feature/home/component/UpcomingSection.kt [hunk 3]
```diff
@@ -121,67 +121,71 @@ private fun LazyGridScope.upcomingSectionHeader(
...
-            }
+            HomeCard(
+                url = item.imageUrl,
+                contentDescription = null,
+                isSaved = item.isSaved,
+                onSavedClick = { onUpcomingItemSaveClicked(item) },
+                onClick = { onUpcomingItemClicked(item) },
+                modifier = Modifier
+                    .aspectRatio(0.8f)
+                    .padding(
```
Comment (MuhammedEdrees) [inline ui/src/main/java/com/baghdad/ui/feature/home/component/UpcomingSection.kt]: The whole else branch is unnecessary since this is loading content only.

File: viewmodel/src/main/java/com/baghdad/viewmodel/categories/CategoriesState.kt
Comment (MuhammedEdrees) [inline viewmodel/src/main/java/com/baghdad/viewmodel/categories/CategoriesState.kt:1]: What does this file have to do with the pr?

File: viewmodel/src/main/java/com/baghdad/viewmodel/home/HomeScreenState.kt [hunk 4]
```diff
@@ -11,11 +11,10 @@ data class HomeScreenState(
     val topRatingItems: List<TopRatingItemUiState> = emptyList(),
     val isContinueWatchingLoading: Boolean = true,
     val continueWatchingItems: List<ContinueWatchingItemUiState> = emptyList(),
-    val isUpcomingGenresLoading: Boolean = true,
```
Comment (MuhammedEdrees) [inline viewmodel/src/main/java/com/baghdad/viewmodel/home/HomeScreenState.kt:14]: Why did you remove this flag?

**Review by MuhammedEdrees — CHANGES_REQUESTED** [review]
Great effort fatma. Check the comments below.
Also i noticed that the upcoming section isn't visible when screen is initially loading.

**Review by MuhammedEdrees — APPROVED** [review]

**Review by FaresM0hamed — APPROVED** [review]

**Review by Malak187 — APPROVED** [review]
