### PR TITLE
Fix/#699 login screen and validation

### LINKED ISSUE #699: Solve enable button of login and make field not accept space of blank value

### LINKED ISSUE #700: Password validation problem make it more than 32

### LINKED ISSUE #705: Show network error in snack bar when any error occur (mapper exception issue) -> Login & Profile

### PR DESCRIPTION
**Pull request by omer1998**
## Fix and improve validation logic of the login process
- put validation logic in use case
- implement testing for the validation logic
- remove unnecessary restriction on user input
- make mask character to be *
- fix logout error message when there is no internet when he logged out
- handle retry action when trying to logout
[login_credential.webm](https://github.com/user-attachments/assets/0e33364c-25fe-40cd-aea6-a9dcddbe6db2)
[logout.webm](https://github.com/user-attachments/assets/e00ad43b-a4a3-47dd-a034-0945ab966c53)

### CODE REVIEW

**Review by karrar-abbas — DISMISSED** [review]

**Comment by Farah315** [comment]
according to the video there a point i think we can improve it

- the stars are not in the middle

image

File: domain/src/main/java/com/baghdad/domain/exception/AppException.kt [hunk 1]
```diff
@@ -9,4 +9,7 @@ class UnAuthorizedException() : NetworkException()
 class NoInternetException() : NetworkException()
 class UnKnownNetworkException() : NetworkException()
 class StorageFullException() : LocalDataBaseException()
-class InValidUserCredentialException() : NetworkException()
+open class AuthenticationException() : AppException()
+class InValidPasswordException() : AuthenticationException()
+class EmptyFieldException() : AuthenticationException()
```
Comment (Farah315) [inline domain/src/main/java/com/baghdad/domain/exception/AppException.kt:14]: actually, i don't know if this validation is necessary, cuz the login button won't be enabled if the input contains only spaces  u're already using .trim() before checking the fields

**Review by Farah315 — COMMENTED** [review]
great job just check the comment

File: domain/src/main/java/com/baghdad/domain/exception/AppException.kt (hunk 1 above)
Comment (omer1998) [reply domain/src/main/java/com/baghdad/domain/exception/AppException.kt:14]: this is business logic not related to the ui

**Comment by omer1998** [comment]
image
image
i think in the design looks not in the center
@Farah315

**Review by Farah315 — APPROVED** [review]
great job

**Review by MahmoodTarek — APPROVED** [review]
Great work

**Review by Arzo-zi — APPROVED** [review]
