### PR TITLE
Fix/ reset genre filter on tab switch in TopRatingScreen and ViewModel

### LINKED ISSUE #369: Reset genre filter on tab switch

### PR DESCRIPTION
**Pull request by abdulazizacc**
In this PR we improve genre filtering scroll state across tab changing

[genress.webm](https://github.com/user-attachments/assets/6aa22802-efa9-4eae-a5ec-c8254105670f)

### CODE REVIEW

**Review by Malak187 — APPROVED** [review]
well done aziz

File: design_system/src/main/java/com/baghdad/design_system/component/Tab.kt [hunk 1]
```diff
@@ -65,8 +67,7 @@ fun Tab(
                 .padding(horizontal = 24.dp)
                 .animateContentSize(tween(ANIMATION_DURATION))
                 .noRippleClickable { onClick() }
-                .then(underlineModifier)
-            ,
+                .then(underlineModifier),
```
Comment (omer1998) [inline design_system/src/main/java/com/baghdad/design_system/component/Tab.kt:70]: i wonder why use then here while you don't perform any logic to apply this modifier

**Review by omer1998 — APPROVED** [review]
great work azize

File: design_system/src/main/java/com/baghdad/design_system/component/Tab.kt (hunk 1 above)
Comment (abdulazizacc) [reply design_system/src/main/java/com/baghdad/design_system/component/Tab.kt:70]: Well you do not need to apply any logic to use `.then()` we usually use it when we wanna add modifier inside another one

**Review by ABDULLAHHG — APPROVED** [review]
