### PR TITLE
Fix/#836 home popular section weirdly twitches when scrolling between two cards

### LINKED ISSUE #836: Fix home popular section weird twitching when switching between items.

### PR DESCRIPTION
**Pull request by MuhammedEdrees**

### CODE REVIEW

File: design_system/src/main/java/com/baghdad/design_system/component/CarousalDot.kt [hunk 1]
```diff
@@ -30,8 +31,10 @@ fun CarousalDot(
     highlightedSize: Dp = 7.dp,
     defaultSize: Dp= 5.dp
 ) {
+    val carouselMinHeight = maxOf(highlightedSize, defaultSize)
+
     LazyRow(
-        modifier = modifier,
+        modifier = modifier.heightIn(min = carouselMinHeight),
```
Comment (omer1998) [inline design_system/src/main/java/com/baghdad/design_system/component/CarousalDot.kt:37]: i don't understand your intention here 
if we put modifier.heightIn(min = 7.dp) what is the problem ?

**Review by omer1998 — APPROVED** [review]

File: design_system/src/main/java/com/baghdad/design_system/component/CarousalDot.kt (hunk 1 above)
Comment (MuhammedEdrees) [reply design_system/src/main/java/com/baghdad/design_system/component/CarousalDot.kt:37]: The issue was in carousel dots when animating between selected size and default size when scrolling the size is temporarily something between selected and default size which causes all content under it to go slightly up and back down. Adding size constraint will help mitigate the issue by defining at least a min size which is the bigger of two sizes ensuring that size will never be smaller than this value.

**Review by Malak187 — APPROVED** [review]

**Review by FaresM0hamed — APPROVED** [review]
