### PR TITLE
Fix/#694 fix caching interceptor

### LINKED ISSUE #694: fix caching interceptor

### PR DESCRIPTION
**Pull request by omer1998**
### what has been done
- exclude certain routes for cache
- exclude http methods other than get to be cached
- not caching unsuccessful requests

this video demonstrates no caching when adding removing list
[fix_caching.webm](https://github.com/user-attachments/assets/81a5ffe3-3418-4673-8769-a9b5e69fe095)

### CODE REVIEW

File: remote_datasource/src/main/java/com/baghdad/remoteDataSource/interceptor/CacheInterceptor.kt [hunk 1]
```diff
@@ -6,6 +6,14 @@ import okhttp3.Response
 class CacheInterceptor : Interceptor {
```
Comment (Farah315) [inline remote_datasource/src/main/java/com/baghdad/remoteDataSource/interceptor/CacheInterceptor.kt:6]: can u use companion object to avoid write hard coded strings?

**Review by MuhammedEdrees — APPROVED** [review]

**Review by MahmoodTarek — APPROVED** [review]
Great work

**Review by Arzo-zi — APPROVED** [review]
