### PR TITLE
Fix/#134 change filter button size

### LINKED ISSUE #134: Primary Bottom Width
Primary Bottom width less than design
[Primary Bottom][(url](https://www.figma.com/design/M8nGARxOa4zTNUGPoDMHHo/Novix?node-id=1055-10150&t=MsDFtxt1TP2SfCe2-4))

Image

### PR DESCRIPTION
**Pull request by Farah315**
image

### CODE REVIEW

**Review by Arzo-zi — DISMISSED** [review]

**Comment by FaresM0hamed** [comment]
Please Rename Pr to match our convention

File: ui/src/main/java/com/baghdad/ui/feature/search/component/SearchTextField.kt [hunk 1]
```diff
@@ -58,7 +58,7 @@ fun SearchTextField(
             AnimatedVisibility(searchTab == SearchTab.MOVIES || searchTab == SearchTab.TV_SHOWS || query.isBlank()) {
                 Box(
                     modifier = Modifier
-                        .size(48.dp)
+                        .size(50.dp)
                         .aspectRatio(1f)
```
Comment (amnah44) [inline ui/src/main/java/com/baghdad/ui/feature/search/component/SearchTextField.kt]: The aspect ratio has no effect here. We should use constraints or dynamic sizing instead, as the current code is redundant.

**Review by MahmoodTarek — DISMISSED** [review]

**Review by MahmoodTarek — APPROVED** [review]
good job Farah

**Review by MuhammedEdrees — APPROVED** [review]
Nice

**Review by abdulazizacc — APPROVED** [review]
