### PR TITLE
Fix/#254 gallery screen colors in dark mode and fix width between text and back icon

### LINKED ISSUE #254: galley screen colors in dark mode

### PR DESCRIPTION
**Pull request by fatmahgazy**
- **Fix Gallery Screen Colors In Dark Mode and Width Between Text And Back Icon**

**Dark mood:** 

Screenshot_2025-07-18-21-58-04-919_com baghdad novix

**Light mood:**

Screenshot_2025-07-18-21-58-13-370_com baghdad novix

### CODE REVIEW

File: ui/src/main/java/com/baghdad/ui/feature/actorGallery/GalleryScreen.kt [hunk 1]
```diff
@@ -63,8 +66,18 @@ fun ActorGalleryScreenContent(
...
+        .background(Theme.color.surface)
+            .dropShadow(
+                color = Theme.color.primary,
+                alpha = 0.08f,
+                offsetX = (-210).dp,
+                offsetY = (18).dp,
+                shape = RectangleShape,
+                blur = 336.dp
+            )
         .statusBarsPadding()) {
```
Comment (Malak187) [inline ui/src/main/java/com/baghdad/ui/feature/actorGallery/GalleryScreen.kt]: add navigationbarpadding here, also a vertical padding just like the design

**Review by Malak187 — CHANGES_REQUESTED** [review]

**Review by omer1998 — DISMISSED** [review]
great work fatma

**Review by Malak187 — DISMISSED** [review]

File: ui/src/main/java/com/baghdad/ui/feature/actorGallery/GalleryScreen.kt [hunk 2]
```diff
@@ -60,12 +63,24 @@ fun GalleryScreen(
 
 @Composable
 fun ActorGalleryScreenContent(
-    uiState: ActorGalleryScreenState,
-    listner: ActorGalleryViewModel
+    uiState: ActorGalleryScreenState, listner: ActorGalleryViewModel
```
Comment (MuhammedEdrees) [inline ui/src/main/java/com/baghdad/ui/feature/actorGallery/GalleryScreen.kt]: change type to interaction listener interface

**Review by omer1998 — APPROVED** [review]

**Review by MuhammedEdrees — APPROVED** [review]

**Review by Malak187 — APPROVED** [review]

**Review by Arzo-zi — APPROVED** [review]
