### PR TITLE
Fix/#407 authentication screens

### LINKED ISSUE #407: Fix authentication screens bugs

### LINKED ISSUE #437: Login screen appears for a sec when opening the app
https://github.com/user-attachments/assets/dd485685-8fe4-4dc6-a6c9-ffb23775e05e

### LINKED ISSUE #443: Extra padding in login screen
Image

### PR DESCRIPTION
**Pull request by omer1998**
## what has been done
- fix authentication screens bugs
- add extra validation for user input 
- better logic to handle which screen (home/ login) to show first
- fix extra padding in login screen
- showing snack bar based on user events

https://github.com/user-attachments/assets/053bd4b7-d2a1-40be-8166-42112302988b

https://github.com/user-attachments/assets/f07ae7af-a11f-4146-b508-75d2ad7ef8a7

### CODE REVIEW

**Review by karrar-abbas — DISMISSED** [review]
Add screenshots or videos about your Pr
You should fix build check test.

File: ui/src/main/java/com/baghdad/ui/feature/authentication/LoginScreen.kt [hunk 1]
```diff
@@ -168,6 +170,7 @@ private fun LoginForm(
 
     NovixTextField(
         label = stringResource(com.baghdad.ui.R.string.password),
+        keyBoardOptions = KeyboardOptions(autoCorrectEnabled = false),
```
Comment (MuhammedEdrees) [inline ui/src/main/java/com/baghdad/ui/feature/authentication/LoginScreen.kt]: What does this achieve?

Comment (omer1998) [reply ui/src/main/java/com/baghdad/ui/feature/authentication/LoginScreen.kt]: @karrar-abbas اي مو تدلل

**Review by Hasa9nAli — DISMISSED** [review]
Great work doctor ❤️

**Review by MuhammedEdrees — DISMISSED** [review]
Nice work

**Review by MuhammedEdrees — APPROVED** [review]

**Review by Malak187 — APPROVED** [review]

**Review by FaresM0hamed — APPROVED** [review]
