### PR TITLE
Fix/#841 fix bugs in-my lists-and saved list details screens

### LINKED ISSUE #841: Fix bugs in my lists and saved list details screens

### PR DESCRIPTION
**Pull request by Malak187**
- Fix paddings 
- Add background blur
- Add trim function to the saved list screen title and specify max length for that title

### CODE REVIEW

File: ui/src/main/java/com/baghdad/ui/feature/component/bottomSheet/AddListBottomSheet.kt [hunk 1]
```diff
@@ -124,6 +124,7 @@ private fun AddListBottomSheetContent(
         )
         NovixTextField(
             value = listName,
+            maxLength = 82,
```
Comment (FaresM0hamed) [inline ui/src/main/java/com/baghdad/ui/feature/component/bottomSheet/AddListBottomSheet.kt]: Why 82 ?

**Review by FaresM0hamed — DISMISSED** [review]

**Review by MuhammedEdrees — DISMISSED** [review]
3aaaash geddannnn 🥁

File: ui/src/main/java/com/baghdad/ui/feature/component/bottomSheet/AddListBottomSheet.kt (hunk 1 above)
Comment (MuhammedEdrees) [reply ui/src/main/java/com/baghdad/ui/feature/component/bottomSheet/AddListBottomSheet.kt]: انهي اروش ٨٠ ولا ٨٢

**Review by MuhammedEdrees — APPROVED** [review]

**Review by FaresM0hamed — APPROVED** [review]

File: ui/src/main/java/com/baghdad/ui/feature/component/bottomSheet/AddListBottomSheet.kt (hunk 1 above)
Comment (FaresM0hamed) [reply ui/src/main/java/com/baghdad/ui/feature/component/bottomSheet/AddListBottomSheet.kt]: اقتنعت 😂

File: ui/src/main/java/com/baghdad/ui/feature/component/bottomSheet/AddListBottomSheet.kt [hunk 2]
```diff
@@ -124,6 +124,7 @@ private fun AddListBottomSheetContent(
         )
         NovixTextField(
             value = listName,
+            maxLength = 100,
```
Comment (omer1998) [inline ui/src/main/java/com/baghdad/ui/feature/component/bottomSheet/AddListBottomSheet.kt:127]: if you make it as a constant that represent the limit may be a good idea ? what do you think ?

**Review by omer1998 — APPROVED** [review]
good job malak

**Review by Hasa9nAli — APPROVED** [review]
