### PR TITLE
Fix/#450 movie details screen bugs

### LINKED ISSUE #450: Fix movie details screen bugs
https://thechance-workspace.slack.com/archives/C08TJ3YCJD6/p1753556071847419

### PR DESCRIPTION
**Pull request by MuhammedEdrees**
- Various bug fixes and enhancements for movie details screen

https://github.com/user-attachments/assets/b324f52d-ba54-419d-a84c-cabff4011680

### CODE REVIEW

**Review by abdulazizacc — DISMISSED** [review]
great job man 👏👏

**Review by MahmoodTarek — DISMISSED** [review]
Great work Edrees

**Review by Malak187 — APPROVED** [review]

**Review by Malak187 — DISMISSED** [review]
Well done edrees

**Review by fatmahgazy — DISMISSED** [review]

**Review by ABDULLAHHG — APPROVED** [review]

File: remote_datasource/src/main/java/com/baghdad/remoteDataSource/RemoteMovieDataSourceImpl.kt [hunk 1]
```diff
@@ -83,7 +83,7 @@ class RemoteMovieDataSourceImpl(
         return handleRequest<MovieImageResponse>(
             apiCall = { movieApiService.getMovieImages(movieId) },
             logger = logger,
-        ).backdrops?.map { it.filePath.orEmpty() }.orEmpty()
+        ).backdrops?.map { "https://image.tmdb.org/t/p/w500" + it.filePath.orEmpty() }.orEmpty()
```
Comment (Hasa9nAli) [inline remote_datasource/src/main/java/com/baghdad/remoteDataSource/RemoteMovieDataSourceImpl.kt:86]: can we use that as const ?

File: ui/src/main/java/com/baghdad/ui/feature/movieDetails/MovieDetailsScreen.kt [hunk 2]
```diff
@@ -195,13 +196,12 @@ private fun MovieDetailsContent(
         ) {
             LazyVerticalGrid(
                 state = lazyState,
-                columns = GridCells.Fixed(2),
+                columns = GridCells.Adaptive(150.dp),
```
Comment (Hasa9nAli) [inline ui/src/main/java/com/baghdad/ui/feature/movieDetails/MovieDetailsScreen.kt:199]: great

**Review by Hasa9nAli — APPROVED** [review]

File: viewmodel/src/main/java/com/baghdad/viewmodel/episodeDetails/EpisodeDetailsViewModel.kt [hunk 3]
```diff
@@ -113,9 +113,7 @@ class EpisodeDetailsViewModel(
     }
 
     override fun onRateEpisodeClick() {
-        updateState {
```
Comment (Farah315) [inline viewmodel/src/main/java/com/baghdad/viewmodel/episodeDetails/EpisodeDetailsViewModel.kt:116]: i have small question why u remove it and just put todo,, is this because it is not required?

**Review by Farah315 — APPROVED** [review]

File: viewmodel/src/main/java/com/baghdad/viewmodel/episodeDetails/EpisodeDetailsViewModel.kt (hunk 3 above)
Comment (MuhammedEdrees) [reply viewmodel/src/main/java/com/baghdad/viewmodel/episodeDetails/EpisodeDetailsViewModel.kt:116]: Correct, I think it would be better to disable these button or at least remove any unnecessary functionality from them till they are implemented.

File: remote_datasource/src/main/java/com/baghdad/remoteDataSource/RemoteMovieDataSourceImpl.kt (hunk 1 above)
Comment (MuhammedEdrees) [reply remote_datasource/src/main/java/com/baghdad/remoteDataSource/RemoteMovieDataSourceImpl.kt:86]: Yes it would be much better but it's a refactor that needs to be done across all remote source for consistency.
