### PR TITLE
Fix/#492-fix-domain-module-unit-test

### LINKED ISSUE #492: Fix Domain Module Unit Test

### PR DESCRIPTION
**Pull request by Farah315**
**Hi there this pr are fixed domain module unit test by change fun name and using google Truth**

### CODE REVIEW

File: domain/src/test/java/com/baghdad/domain/usecase/movie/GetMovieGalleryUseCaseTest.kt [hunk 1]
```diff
@@ -20,10 +18,10 @@ class GetMovieGalleryUseCaseTest {
     }
 
     @Test
```
Comment (FaresM0hamed) [inline domain/src/test/java/com/baghdad/domain/usecase/movie/GetMovieGalleryUseCaseTest.kt:20]: Where is Assertion ? , Or what is this fun actually test ?

File: domain/src/test/java/com/baghdad/domain/usecase/movie/GetMovieGalleryUseCaseTest.kt [hunk 2]
```diff
@@ -34,46 +32,38 @@ class GetMovieGalleryUseCaseTest {
...
-            posterImageURL = "https://example.com/very/long/path/to/the/movie/poster/image" +
-                    "/with/many/subdirectories/and/parameters?query=123&param=abc"
-        )
-        coEvery { movieRepository.getMovieDetails(movieId) } returns longUrlMovie
+        val movieId = 4L
+        val longUrl = "https://example.com/images/poster/with/a/very/long/path?param=value"
+        coEvery { movieRepository.getMovieImages(movieId) } returns listOf(longUrl)
 
         // When
         val result = getMovieGalleryUseCase(movieId)
```
Comment (FaresM0hamed) [inline domain/src/test/java/com/baghdad/domain/usecase/movie/GetMovieGalleryUseCaseTest.kt]: Where is Assertion?

File: domain/src/test/java/com/baghdad/domain/usecase/movie/GetUpcomingMoviesUseCaseTest.kt [hunk 3]
```diff
@@ -43,22 +43,15 @@ class GetUpcomingMoviesUseCaseTest {
...
+        coEvery { movieRepository.getUpcomingMovies(genreId) } returns movies
 
         // When
-        val result = useCase(page, genreId)
+        val result = useCase(genreId)
 
         // Then
-        assertEquals(expectedResult, result)
-        coVerify(exactly = 1) { movieRepository.getUpcomingMovies(page, genreId) }
+        assertEquals(movies, result)
```
Comment (FaresM0hamed) [inline domain/src/test/java/com/baghdad/domain/usecase/movie/GetUpcomingMoviesUseCaseTest.kt]: We Use Google Truth Not Junit

**Review by FaresM0hamed — CHANGES_REQUESTED** [review]
1- Replace all test funs name to match our convention
2- Use Google Truth Instead of Junit 

image

File: domain/src/test/java/com/baghdad/domain/usecase/movie/GetMovieGalleryUseCaseTest.kt (hunk 2 above)
Comment (omer1998) [reply domain/src/test/java/com/baghdad/domain/usecase/movie/GetMovieGalleryUseCaseTest.kt]: faris you can expand the code below to look for the actual assertion

**Review by omer1998 — DISMISSED** [review]
good job, seems logical and good to me

File: domain/src/test/java/com/baghdad/domain/usecase/movie/GetMovieGalleryUseCaseTest.kt [hunk 4]
```diff
@@ -34,46 +32,38 @@ class GetMovieGalleryUseCaseTest {
...
 
         // Then
-        assertThat(result[0]).isEqualTo("https://example.com/movies/戦争と平和.jpg")
+        assertThat(result).containsExactly("https://example.com/ポスター.jpg")
     }
 
     @Test
-    fun `getMovieGalleryUseCase returns list with long URL`() = runTest {
+    fun `getMovieGalleryUseCase returns long URL`() = runTest {
```
Comment (fatmahgazy) [inline domain/src/test/java/com/baghdad/domain/usecase/movie/GetMovieGalleryUseCaseTest.kt]: you can use convention  function name should when to be it more clear

File: domain/src/test/java/com/baghdad/domain/usecase/movie/GetMovieGalleryUseCaseTest.kt [hunk 5]
```diff
@@ -85,47 +75,37 @@ class GetMovieGalleryUseCaseTest {
...
         getMovieGalleryUseCase(movieId)
 
         // Then
-        coVerify(exactly = 1) { movieRepository.getMovieDetails(movieId) }
+        coVerify(exactly = 1) { movieRepository.getMovieImages(movieId) }
     }
 
     @Test
-    fun `getMovieGalleryUseCase returns different URLs for different movies`() = runTest {
+    fun `getMovieGalleryUseCase returns different images for different movies`() = runTest {
```
Comment (fatmahgazy) [inline domain/src/test/java/com/baghdad/domain/usecase/movie/GetMovieGalleryUseCaseTest.kt]: same

File: domain/src/test/java/com/baghdad/domain/usecase/movie/GetMovieGalleryUseCaseTest.kt [hunk 6]
```diff
@@ -85,47 +75,37 @@ class GetMovieGalleryUseCaseTest {
...
 
         // Then
         assertThat(result1).isNotEqualTo(result2)
-        assertThat(result1[0]).endsWith("shawshank.jpg")
-        assertThat(result2[0]).endsWith("another.jpg")
     }
 
     @Test
-    fun `getMovieGalleryUseCase returns secure HTTPS URLs`() = runTest {
+    fun `getMovieGalleryUseCase returns HTTPS URLs`() = runTest {
```
Comment (fatmahgazy) [inline domain/src/test/java/com/baghdad/domain/usecase/movie/GetMovieGalleryUseCaseTest.kt]: same

**Review by fatmahgazy — DISMISSED** [review]
Good Work

File: domain/src/test/java/com/baghdad/domain/usecase/movie/GetMovieGalleryUseCaseTest.kt (hunk 1 above)
Comment (Farah315) [reply domain/src/test/java/com/baghdad/domain/usecase/movie/GetMovieGalleryUseCaseTest.kt:20]: @FaresM0hamed here the assertion,it obviously returns a list of poster url
image

File: domain/src/test/java/com/baghdad/domain/usecase/actor/GetActorMoviesUseCaseTest.kt [hunk 7]
```diff
@@ -93,7 +93,7 @@ class GetActorMoviesUseCaseTest {
     }
 
     @Test
-    fun `getActorMoviesUseCase returns movies with minimal fields`() = runTest {
+    fun `getActorMoviesUseCase() should return movies with minimal fields when data is sparse`() = runTest {
```
Comment (karrar-abbas) [inline domain/src/test/java/com/baghdad/domain/usecase/actor/GetActorMoviesUseCaseTest.kt:96]: Why you add '()' in function names?

**Review by karrar-abbas — APPROVED** [review]

File: domain/src/test/java/com/baghdad/domain/usecase/actor/GetActorMoviesUseCaseTest.kt (hunk 7 above)
Comment (Farah315) [reply domain/src/test/java/com/baghdad/domain/usecase/actor/GetActorMoviesUseCaseTest.kt:96]: image 
my overthinking😖

**Review by karrar-abbas — APPROVED** [review]

**Review by MuhammedEdrees — APPROVED** [review]
Great job on the coverage. Keep going.

File: domain/src/test/java/com/baghdad/domain/usecase/actor/GetActorGalleryUseCaseTest.kt [hunk 8]
```diff
@@ -21,7 +21,7 @@ class GetActorGalleryUseCaseTest {
     }
 
     @Test
-    fun `getActorGalleryUseCase should return actor gallery`() = runTest {
+    fun `getActorGalleryUseCase() should return actor gallery when called with valid actorId`() = runTest {
```
Comment (abdulazizacc) [inline domain/src/test/java/com/baghdad/domain/usecase/actor/GetActorGalleryUseCaseTest.kt:24]: are you sure that we should put () inside the naming?

**Review by FaresM0hamed — APPROVED** [review]
