### PR TITLE
Fix/#418 fix tv show details screen

### LINKED ISSUE #418: Fix Tv show details screen

### PR DESCRIPTION
**Pull request by Malak187**
- Hide redundant data in the Ui that are returned from API (null duration, null released date)
- Enhance the flow row behavior in TV shows genres section and seasons episode card
- Round TV show/episode rating values to its first decimal point

### CODE REVIEW

File: ui/src/main/java/com/baghdad/ui/feature/tvShowDetails/component/EpisodesCard.kt [hunk 1]
```diff
@@ -77,25 +81,33 @@ fun EpisodeCard(
...
-                CircleDot(
-                    modifier = Modifier
-                        .align(Alignment.CenterVertically)
-                )
-                Text(
-                    text = releaseDate,
-                    style = Theme.typography.label.small,
-                    color = Theme.color.hint
-                )
+                if (releaseDate != "1 Jan 0001") {
```
Comment (abdulazizacc) [inline ui/src/main/java/com/baghdad/ui/feature/tvShowDetails/component/EpisodesCard.kt:98]: Localize it

File: ui/src/main/res/values-ar/strings.xml [hunk 2]
```diff
@@ -83,7 +83,7 @@
     <string name="trending_people">الممثلون الرائجون</string>
 
     <string name="episodes">عدد الحلقات %1$d </string>
-    <string name="s"> الموسم</string>
+    <string name="s"> الموسم </string>
```
Comment (MahmoodTarek) [inline ui/src/main/res/values-ar/strings.xml:86]: but why you added a space before "الموسم"

**Review by MahmoodTarek — DISMISSED** [review]
Great work Malak

File: ui/src/main/java/com/baghdad/ui/feature/tvShowDetails/component/EpisodesCard.kt (hunk 1 above)
Comment (MahmoodTarek) [reply ui/src/main/java/com/baghdad/ui/feature/tvShowDetails/component/EpisodesCard.kt:98]: I think it's just for the condition, Azaz.  
We need to make sure the releaseDate is not the default value coming from the backend.  
Since it will not be displayed on the screen, we don’t need localization here.

File: ui/src/main/res/values-ar/strings.xml (hunk 2 above)
Comment (Malak187) [reply ui/src/main/res/values-ar/strings.xml:86]: مش قبلها هي بعدها بس معكوسة عشان العربي أظن

File: ui/src/main/java/com/baghdad/ui/feature/tvShowDetails/component/EpisodesCard.kt (hunk 1 above)
Comment (Malak187) [reply ui/src/main/java/com/baghdad/ui/feature/tvShowDetails/component/EpisodesCard.kt:98]: I think we don't need to. When switching to arabic, the date still takes that value. What do u think?

**Review by MahmoodTarek — APPROVED** [review]

**Review by karrar-abbas — APPROVED** [review]

**Review by abdulazizacc — APPROVED** [review]
