### PR TITLE
Fix/#422-missing thumb border in the range slider 

### LINKED ISSUE #442: Missing thumb border in the range slider
Image

### PR DESCRIPTION
**Pull request by fatmahgazy**
- **add thumb border in the range slider**

Screenshot_2025-07-29-17-06-20-305_com baghdad novix

### CODE REVIEW

File: local_datasource/src/main/java/com/baghdad/local_datasource/dataStore/user/userMapper.kt [hunk 1]
```diff
@@ -3,7 +3,6 @@ package com.baghdad.local_datasource.dataStore.user
 import com.baghdad.repository.model.UserDto
 import com.example.application.proto.User
```
Comment (MahmoodTarek) [inline local_datasource/src/main/java/com/baghdad/local_datasource/dataStore/user/userMapper.kt:4]: why you added an unnecessary space in userMapper file !!

File: local_datasource/src/main/java/com/baghdad/local_datasource/dataStore/user/UserSerializer.kt [hunk 2]
```diff
@@ -8,7 +8,6 @@ import kotlinx.coroutines.withContext
 import java.io.InputStream
 import java.io.OutputStream
 
-
```
Comment (MahmoodTarek) [inline local_datasource/src/main/java/com/baghdad/local_datasource/dataStore/user/UserSerializer.kt:11]: same

Comment (MahmoodTarek) [reply local_datasource/src/main/java/com/baghdad/local_datasource/dataStore/user/UserSerializer.kt:11]: you can check what is the changes in the files before pushing

**Review by MahmoodTarek — APPROVED** [review]
Great work Fatma

**Review by Malak187 — APPROVED** [review]
3aaaash

**Review by Hasa9nAli — APPROVED** [review]
Wade
