### PR TITLE
Fix/#459 fix review screen issues

### LINKED ISSUE #459: Fix Review Screen

### PR DESCRIPTION
**Pull request by Malak187**
- Use default placeholder if reviewer has no image.
- Refactor the icon used when there is no reviews.
- Clip the reviewer image to its required radius and wrap the image with a border.

image

image

### CODE REVIEW

**Review by ABDULLAHHG — DISMISSED** [review]

File: entity/src/main/java/com/baghdad/entity/media/Review.kt [hunk 1]
```diff
@@ -7,7 +7,7 @@ data class Review(
     val authorName: String,
     val authorAvatarUrl: String,
     val contentTitle: String,
-    val rating: Float,
+    val rating: Double,
```
Comment (MahmoodTarek) [inline entity/src/main/java/com/baghdad/entity/media/Review.kt:10]: But why did you change the type to Double?  
The only reason to use Double is when you need higher precision (more decimal digits).  
In our case, we only need one decimal place (like 1.5), so Float should be enough.

**Review by MahmoodTarek — DISMISSED** [review]
Great work Malak

File: entity/src/main/java/com/baghdad/entity/media/Review.kt (hunk 1 above)
Comment (Hasa9nAli) [reply entity/src/main/java/com/baghdad/entity/media/Review.kt:10]: good note mahmood

File: remote_datasource/src/main/java/com/baghdad/remoteDataSource/mapper/ReviewResponseMapper.kt [hunk 2]
```diff
@@ -9,7 +9,7 @@ fun ReviewResponse.toDto(): ReviewDto {
         authorName = (authorDetails?.name.takeIf { !it.isNullOrBlank() }) ?: "Guest",
         authorAvatarUrl = ("https://image.tmdb.org/t/p/w500" + authorDetails?.avatarPath.orEmpty()),
```
Comment (Hasa9nAli) [inline remote_datasource/src/main/java/com/baghdad/remoteDataSource/mapper/ReviewResponseMapper.kt:10]: base url should be in const

File: remote_datasource/src/main/java/com/baghdad/remoteDataSource/mapper/ReviewResponseMapper.kt [hunk 3]
```diff
@@ -9,7 +9,7 @@ fun ReviewResponse.toDto(): ReviewDto {
...
         contentTitle = authorDetails?.username ?: "",
-        rating = authorDetails?.rating ?: 0f,
+        rating = authorDetails?.rating ?: 0.0,
         reviewText = content ?: "",
         postedDate = createdAt.takeIf { !it.isNullOrBlank() } ?: "0001-01-01"
```
Comment (Hasa9nAli) [inline remote_datasource/src/main/java/com/baghdad/remoteDataSource/mapper/ReviewResponseMapper.kt:14]: if null we con return it as Unknown ?

File: ui/src/main/java/com/baghdad/ui/feature/component/islamicImage/PlaceHolderReviewerImage.kt [hunk 4]
```diff
@@ -0,0 +1,26 @@
...
+import com.baghdad.design_system.theme.Theme
+
+@Composable
+fun PlaceHolderReviewerImage() {
+    Box(
+        contentAlignment = Alignment.Center,
+    ) {
+        Icon(
+            painter = painterResource(R.drawable.img_reviewer_default),
+            contentDescription = "Default Image",
```
Comment (Hasa9nAli) [inline ui/src/main/java/com/baghdad/ui/feature/component/islamicImage/PlaceHolderReviewerImage.kt]: should using localize (string resource )

File: ui/src/main/java/com/baghdad/ui/feature/review/ReviewScreen.kt [hunk 5]
```diff
@@ -142,8 +143,12 @@ private fun EmptyReviewScreen() {
         contentAlignment = Alignment.Center
     ) {
         EmptySearchState(
-            imagePath = com.baghdad.design_system.R.drawable.ic_empty_review_screen,
-            contentDescription = "No Reviews yet",
+            imagePath = if (isSystemInDarkTheme()) {
+                com.baghdad.design_system.R.drawable.ic_empty_review_screen_dark
+            } else {
+                com.baghdad.design_system.R.drawable.ic_empty_review_screen
```
Comment (Hasa9nAli) [inline ui/src/main/java/com/baghdad/ui/feature/review/ReviewScreen.kt:149]: dont need that make it import com.baghdad.design_system

File: entity/src/main/java/com/baghdad/entity/media/Review.kt (hunk 1 above)
Comment (Farah315) [reply entity/src/main/java/com/baghdad/entity/media/Review.kt:10]: @MahmoodTarek  actually, i agree with u. but there's one point I'd like to clarify ... in java and Kotlin, when we type a decimal literal like `7.7`, it's interpreted as a` Double` by default ,,,so using `Double` can be more convenient because we don't have to keep writing `7.7f` for `Float values` ,,, but `Float` still makes more sense

File: remote_datasource/src/main/java/com/baghdad/remoteDataSource/mapper/ReviewResponseMapper.kt (hunk 2 above)
Comment (Farah315) [reply remote_datasource/src/main/java/com/baghdad/remoteDataSource/mapper/ReviewResponseMapper.kt:10]: @Hasa9nAli in fact we should remove  all the URLs in all Mappers

File: ui/src/main/java/com/baghdad/ui/feature/review/ReviewScreen.kt (hunk 5 above)
Comment (Farah315) [reply ui/src/main/java/com/baghdad/ui/feature/review/ReviewScreen.kt:149]: @Hasa9nAli actually no ,,removing it causes an error since it’s from another module `com.baghdad.design_system`, so the import is required

image

**Review by Farah315 — DISMISSED** [review]
3ashhh ya maloka 👏🏻👏🏻

File: remote_datasource/src/main/java/com/baghdad/remoteDataSource/response/ReviewsResponse.kt [hunk 6]
```diff
@@ -36,5 +36,5 @@ data class MovieAuthorDetails(
     @SerializedName("avatar_path")
     val avatarPath: String? = null,
     @SerializedName("rating")
-    val rating: Float? = null
+    val rating: Double? = null
```
Comment (fatmahgazy) [inline remote_datasource/src/main/java/com/baghdad/remoteDataSource/response/ReviewsResponse.kt:39]: why you use double instead float i think is better using float what do you think?

File: ui/src/main/java/com/baghdad/ui/feature/review/ReviewScreen.kt [hunk 7]
```diff
@@ -142,8 +143,12 @@ private fun EmptyReviewScreen() {
         contentAlignment = Alignment.Center
     ) {
         EmptySearchState(
-            imagePath = com.baghdad.design_system.R.drawable.ic_empty_review_screen,
-            contentDescription = "No Reviews yet",
+            imagePath = if (isSystemInDarkTheme()) {
```
Comment (fatmahgazy) [inline ui/src/main/java/com/baghdad/ui/feature/review/ReviewScreen.kt:146]: I think you can use Animated visabilty instead if statement

File: design_system/src/main/res/drawable/ic_empty_review_screen_dark.xml [hunk 8]
```diff
@@ -0,0 +1,99 @@
...
+                        android:color="#FFF57457" />
+                    <item
+                        android:offset="1"
+                        android:color="#FFC65A42" />
+                </gradient>
+            </aapt:attr>
+        </path>
+        <path
+            android:pathData="M40.37,47.26C37.74,51.81 37.74,57.91 37.74,70.1C37.74,82.3 37.74,88.4 40.37,92.94C42.08,95.92 44.56,98.39 47.53,100.11C52.07,102.73 58.17,102.73 70.37,102.73H83.42C87.26,102.73 90.49,102.73 93.27,102.65L106.21,110.51C107.58,111.34 109.32,110.26 109.18,108.66L108.29,98.76C110.37,97.19 112.12,95.21 113.43,92.94C116.05,88.4 116.05,82.3 116.05,70.1C116.05,57.91 116.05,51.81 113.43,47.26C111.71,44.29 109.24,41.82 106.26,40.1C101.72,37.48 95.62,37.48 83.42,37.48L70.37,37.48C58.17,37.48 52.07,37.48 47.53,40.1C44.56,41.82 42.08,44.29 40.37,47.26Z"
+            android:fillColor="#FFA996"
```
Comment (fatmahgazy) [inline design_system/src/main/res/drawable/ic_empty_review_screen_dark.xml:28]: I think Fill color must be black

File: ui/src/main/java/com/baghdad/ui/feature/review/component/ReviewerHeader.kt [hunk 9]
```diff
@@ -37,8 +41,15 @@ fun ReviewerHeader(
     ) {
         IslamicImage(
             imageUrl = imageUrl,
+            errorContent = { PlaceHolderReviewerImage() },
```
Comment (fatmahgazy) [inline ui/src/main/java/com/baghdad/ui/feature/review/component/ReviewerHeader.kt:45]: It's better not to  leave the content description null

File: ui/src/main/java/com/baghdad/ui/feature/review/ReviewScreen.kt (hunk 5 above)
Comment (Hasa9nAli) [reply ui/src/main/java/com/baghdad/ui/feature/review/ReviewScreen.kt:149]: @Farah315 

you can use that is import above import` com.baghdad.design_system.*`

File: entity/src/main/java/com/baghdad/entity/media/Review.kt (hunk 1 above)
Comment (Malak187) [reply entity/src/main/java/com/baghdad/entity/media/Review.kt:10]: In addition to Farah's note, all ratings in the app in other screen are double so we have to keep consistency 
Second, if you keep it float, you can't round in to the first decimal unless you convert it to double first
So for example instead of writing rating.toDouble.roundToFirstDecimal(). I think it would be more clean to make it double in the first place

File: remote_datasource/src/main/java/com/baghdad/remoteDataSource/mapper/ReviewResponseMapper.kt (hunk 3 above)
Comment (Malak187) [reply remote_datasource/src/main/java/com/baghdad/remoteDataSource/mapper/ReviewResponseMapper.kt:14]: Hamsa told me that rating should be kept as 0

File: remote_datasource/src/main/java/com/baghdad/remoteDataSource/response/ReviewsResponse.kt (hunk 6 above)
Comment (Malak187) [reply remote_datasource/src/main/java/com/baghdad/remoteDataSource/response/ReviewsResponse.kt:39]: Check the conversation above

**Review by Farah315 — DISMISSED** [review]

**Review by ABDULLAHHG — APPROVED** [review]

**Review by MuhammedEdrees — APPROVED** [review]

**Review by FaresM0hamed — APPROVED** [review]
