### PR TITLE
Fix/#511 fix repository test

### LINKED ISSUE #511: Fix Repository Test

### PR DESCRIPTION
**Pull request by abdulazizacc**
Refactor the unit tests and fix the failing ones in repository
image

### CODE REVIEW

**Review by karrar-abbas — DISMISSED** [review]

**Review by omer1998 — DISMISSED** [review]

File: repository/src/test/java/com/baghdad/repository/mapper/ActorMapperTest.kt [hunk 1]
```diff
@@ -0,0 +1,112 @@
...
+        assertThat(result.name).isEqualTo("Test Actor")
+        assertThat(result.profilePictureURL).isEqualTo("/actor_profile.jpg")
+        assertThat(result.biography).isEqualTo("Test actor biography")
+        assertThat(result.birthDate).isEqualTo(LocalDate.parse("1985-03-10"))
+        assertThat(result.deathDate).isNull()
+        assertThat(result.placeOfBirth).isEqualTo("Los Angeles, USA")
+        assertThat(result.headerPictures.size).isEqualTo(2)
+        assertThat(result.headerPictures[0]).isEqualTo("/actor_header1.jpg")
+        assertThat(result.headerPictures[1]).isEqualTo("/actor_header2.jpg")
+        assertThat(result.department).isEqualTo("Acting")
```
Comment (MahmoodTarek) [inline repository/src/test/java/com/baghdad/repository/mapper/ActorMapperTest.kt:30]: Instead of hardcoding the name , Id .... , `789L`  and `"Test Actor"`
you can replace it with
`createMockActorDto.name` and `createMockActorDto.id` 
This makes the test more readable, maintainable, and less error-prone if the fake data changes in the future.

**Review by MahmoodTarek — DISMISSED** [review]
Great work The best Azaz  Ya 3m 
Just small note

**Review by MuhammedEdrees — DISMISSED** [review]

**Review by ABDULLAHHG — DISMISSED** [review]

**Review by MuhammedEdrees — APPROVED** [review]

**Review by FaresM0hamed — APPROVED** [review]

**Review by Farah315 — APPROVED** [review]

**Review by Malak187 — APPROVED** [review]
