### PR TITLE
Fix/#457 episode details screen bugs

### LINKED ISSUE #457: Fix episode details screen bug
https://thechance-workspace.slack.com/archives/C08TJ3YCJD6/p1753556123373159

### PR DESCRIPTION
**Pull request by MuhammedEdrees**
- Various bug fixes and enhancements for episode details screen.

https://github.com/user-attachments/assets/b9491bf2-66f4-428f-88b1-a50af8ac379c

### CODE REVIEW

File: ui/src/main/java/com/baghdad/ui/feature/episodeDetails/EpisodeDetailsScreen.kt [hunk 1]
```diff
@@ -153,7 +153,7 @@ fun EpisodeDetailsContent(
                     }
 
                     item {
-                        Spacer(Modifier.height(84.dp))
+                        Spacer(Modifier.height(128.dp))
```
Comment (MahmoodTarek) [inline ui/src/main/java/com/baghdad/ui/feature/episodeDetails/EpisodeDetailsScreen.kt:156]: IDK,  but did you confirm that this value is correct?

**Review by MahmoodTarek — APPROVED** [review]
The Best Edrees

File: ui/src/main/java/com/baghdad/ui/feature/episodeDetails/component/EpisodeDetailsHeader.kt [hunk 2]
```diff
@@ -34,84 +34,93 @@ fun EpisodeDetailsHeader(
...
+                .border(1.dp, Theme.color.stroke, shape = RoundedCornerShape(16.dp))
+                .padding(12.dp),
     ) {
         Text(
             text = title,
             fontSize = 18.sp,
             style = Theme.typography.title.medium,
             color = Theme.color.title,
-            modifier = Modifier.padding(bottom = 8.dp)
+            modifier = Modifier.padding(bottom = 44.dp),
```
Comment (Hasa9nAli) [inline ui/src/main/java/com/baghdad/ui/feature/episodeDetails/component/EpisodeDetailsHeader.kt:52]: why 44 ?

**Review by Hasa9nAli — APPROVED** [review]
great work edress keep going

File: ui/src/main/java/com/baghdad/ui/feature/episodeDetails/EpisodeDetailsScreen.kt (hunk 1 above)
Comment (MuhammedEdrees) [reply ui/src/main/java/com/baghdad/ui/feature/episodeDetails/EpisodeDetailsScreen.kt:156]: These number is approximation based on eye test. The way this we implemented the image carousel it's hard to verify.

File: ui/src/main/java/com/baghdad/ui/feature/episodeDetails/component/EpisodeDetailsHeader.kt (hunk 2 above)
Comment (MuhammedEdrees) [reply ui/src/main/java/com/baghdad/ui/feature/episodeDetails/component/EpisodeDetailsHeader.kt:52]: To match figma design. For some reason there is a big space under the episode title.

File: ui/src/main/java/com/baghdad/ui/feature/episodeDetails/component/EpisodeHeaderWithDetailsCard.kt [hunk 3]
```diff
@@ -27,32 +27,34 @@ import com.baghdad.viewmodel.episodeDetails.EpisodeDetailsScreenState
...
         )
 
         Column(
-            modifier = Modifier
-                .align(Alignment.BottomCenter)
-                .offset(y = 82.dp)
+            modifier =
+                Modifier
+                    .align(Alignment.BottomCenter)
+                    .offset(y = 128.dp),
```
Comment (fatmahgazy) [inline ui/src/main/java/com/baghdad/ui/feature/episodeDetails/component/EpisodeHeaderWithDetailsCard.kt:45]: Can we use offset in certain situations, like here? Or will it negatively affect on adaptive or device rotation behavior?

**Review by fatmahgazy — APPROVED** [review]
Great work 👏
