### PR TITLE
Fix/#586 background glow

### LINKED ISSUE #586: issue : no blur in home screen

### LINKED ISSUE #598: Implement background glow

### PR DESCRIPTION
**Pull request by ABDULLAHHG**
implement background glow

[background_blur.webm](https://github.com/user-attachments/assets/e3558ac5-8059-4796-9285-a3fc5d205a28)

### CODE REVIEW

File: ui/src/main/java/com/baghdad/ui/feature/search/SearchScreen.kt [hunk 1]
```diff
@@ -126,10 +128,11 @@ fun SearchContent(
                 onActionClick = listener::onSnackBarActionLabelClick,
             )
         },
-    ) {
+        backgroundBlur = {
+            BackgroundBlur(modifier = Modifier.zIndex(999f))
```
Comment (Farah315) [inline ui/src/main/java/com/baghdad/ui/feature/search/SearchScreen.kt]: why .zIndex(999f) can u explain it to me?

**Review by Farah315 — COMMENTED** [review]
i dunno know if the problem is on my side, but the popular section was not there when I checked the branch

WhatsApp Image 2025-08-05 at 13 37 56_4abf9522

File: ui/src/main/java/com/baghdad/ui/feature/search/SearchScreen.kt (hunk 1 above)
Comment (ABDULLAHHG) [reply ui/src/main/java/com/baghdad/ui/feature/search/SearchScreen.kt]: cause i want it to be uppove everything 
it work with box only

**Review by omer1998 — DISMISSED** [review]
good job aboud

**Review by MuhammedEdrees — APPROVED** [review]
Great work

**Review by abdulazizacc — APPROVED** [review]
great jobb

File: design_system/src/main/java/com/baghdad/design_system/component/Scaffold.kt [hunk 2]
```diff
@@ -24,18 +28,20 @@ fun Scaffold(
     snackbar: (@Composable () -> Unit)? = null,
     bottomBar: (@Composable () -> Unit)? = null,
     bottomBarHeight: Int = 70,
```
Comment (Farah315) [inline design_system/src/main/java/com/baghdad/design_system/component/Scaffold.kt:30]: i suggest moving` bottomBarHeight`  under `isLoading`, since it's a simple integer configuration.
this keeps it grouped with the other non-composable parameters, instead of placing it between composable ui components,,,it makes the function signature easier to read and maintain

File: ui/src/main/java/com/baghdad/ui/feature/actorGallery/GalleryScreen.kt [hunk 3]
```diff
@@ -92,8 +94,10 @@ fun ActorGalleryScreenContent(
                     .padding(vertical = 8.dp)
                     .padding(top = 12.dp)
             ) {}
-        }
-    ) {
+        },
+        backgroundBlur = {
+            BackgroundBlur()
+        }) {
```
Comment (Farah315) [inline ui/src/main/java/com/baghdad/ui/feature/actorGallery/GalleryScreen.kt:100]: i think u here need sime space

**Review by Farah315 — COMMENTED** [review]
great job aboud just u need  a little format

**Review by omer1998 — APPROVED** [review]
