### PR TITLE
fix/#440-movie-details-header-card-offset

### LINKED ISSUE #440: Movie details header card offset
Image

### PR DESCRIPTION
**Pull request by Arzo-zi**
Screenshot 2025-07-30 at 4 55 54 pm
Screenshot 2025-07-30 at 4 55 41 pm
Screenshot 2025-07-30 at 7 01 09 pm
Screenshot 2025-07-30 at 7 02 03 pm

### CODE REVIEW

**Review by MuhammedEdrees — APPROVED** [review]

File: ui/src/main/java/com/baghdad/ui/feature/actorDetails/ActorDetailsScreen.kt [hunk 1]
```diff
@@ -164,6 +166,8 @@ fun ActorDetailsContent(
 
                 ActorHeaderWithDetailsCard(uiState = uiState)
 
+                Spacer(Modifier.height(84.dp))
```
Comment (abdulazizacc) [inline ui/src/main/java/com/baghdad/ui/feature/actorDetails/ActorDetailsScreen.kt:169]: why 84

File: ui/src/main/java/com/baghdad/ui/feature/actorDetails/component/CardInfo.kt [hunk 2]
```diff
@@ -23,41 +24,43 @@ fun CardInfo(
...
-                text = birthPlace,
-                painter = painterResource(R.drawable.ic_birth_place),
-                contentDescription = "birth place",
-            )
+            Row {
+                CircleDot(modifier = Modifier.align(Alignment.CenterVertically))
+                IconTextInfo(
+                    text = birthPlace,
+                    painter = painterResource(R.drawable.ic_birth_place),
+                    contentDescription = "birth place",
```
Comment (abdulazizacc) [inline ui/src/main/java/com/baghdad/ui/feature/actorDetails/component/CardInfo.kt:43]: I think this text should be localized

**Review by Malak187 — APPROVED** [review]

**Review by abdulazizacc — APPROVED** [review]
good job zinah

**Review by MahmoodTarek — APPROVED** [review]

File: ui/src/main/java/com/baghdad/ui/feature/actorDetails/ActorDetailsScreen.kt (hunk 1 above)
Comment (Arzo-zi) [reply ui/src/main/java/com/baghdad/ui/feature/actorDetails/ActorDetailsScreen.kt:169]: because i updated the movie to use the offset so in this case should a spacer
