### PR TITLE
Fix/#402 fix top rating screen bugs

### LINKED ISSUE #401: Fix Top Rating screen bugs

### PR DESCRIPTION
**Pull request by Malak187**
- Fixed the issue movie/tv show genres are reset every time i switch tabs
- Preserved scroll position per tab and auto-scrolled to the selected genre when switching between Movies and TV shows.
- Add required border under the Movies/TvShows tabs. 

**Before:**

https://github.com/user-attachments/assets/e61819d6-afeb-49f4-8f74-d88a4e17b95b

**After**

https://github.com/user-attachments/assets/32d38c33-b807-4f59-8974-36ab0103e0b4

**Before**
image

**After**
image

### CODE REVIEW

**Review by ABDULLAHHG — DISMISSED** [review]

File: viewmodel/src/main/java/com/baghdad/viewmodel/topRating/TopRatingViewModel.kt [hunk 1]
```diff
@@ -122,17 +131,17 @@ class TopRatingViewModel(
 
     override fun onSelectedTab(selectedTab: TopRatingTab) {
         updateState {
-            it.copy(selectedTab = selectedTab, selectedGenreId = null)
+            it.copy(selectedTab = selectedTab)
```
Comment (abdulazizacc) [inline viewmodel/src/main/java/com/baghdad/viewmodel/topRating/TopRatingViewModel.kt:134]: Are you sure it will go back to `All` after this change?

**Review by MuhammedEdrees — DISMISSED** [review]
Well done

**Review by MahmoodTarek — DISMISSED** [review]
Great work Malak

**Review by karrar-abbas — DISMISSED** [review]

**Review by Arzo-zi — DISMISSED** [review]

**Review by MuhammedEdrees — APPROVED** [review]
Well done

**Review by Farah315 — APPROVED** [review]
Good job👏🏻

**Review by karrar-abbas — APPROVED** [review]
