### PR TITLE
Fix/#600 genre chip appear when its content is empty

### LINKED ISSUE #600: Unify genres section across app screen and make All chip disappear when genres list is empty

### PR DESCRIPTION
**Pull request by ABDULLAHHG**
fix genere appear with empty content 

[continue watching.webm](https://github.com/user-attachments/assets/6624b5fb-c067-416d-b956-bac6eac17602)

### CODE REVIEW

**Review by MuhammedEdrees — APPROVED** [review]

File: domain/src/main/java/com/baghdad/domain/usecase/continueWatching/GetCurrentContinueWatchingMovieGenres.kt [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+
+import com.baghdad.domain.repository.ContinueWatchingRepository
+import com.baghdad.domain.usecase.genre.GetGenresUseCase
+import com.baghdad.entity.media.Genre
+import kotlinx.coroutines.ExperimentalCoroutinesApi
+import kotlinx.coroutines.flow.Flow
+import kotlinx.coroutines.flow.mapLatest
+import javax.inject.Inject
+
+class GetCurrentContinueWatchingMovieGenres @Inject constructor(
```
Comment (abdulazizacc) [inline domain/src/main/java/com/baghdad/domain/usecase/continueWatching/GetCurrentContinueWatchingMovieGenres.kt:11]: I think the naming should end up with usecase

File: domain/src/main/java/com/baghdad/domain/usecase/continueWatching/GetCurrentContinueWatchingTvShowGenres.kt [hunk 2]
```diff
@@ -0,0 +1,23 @@
...
+
+import com.baghdad.domain.repository.ContinueWatchingRepository
+import com.baghdad.domain.usecase.genre.GetGenresUseCase
+import com.baghdad.entity.media.Genre
+import kotlinx.coroutines.ExperimentalCoroutinesApi
+import kotlinx.coroutines.flow.Flow
+import kotlinx.coroutines.flow.mapLatest
+import javax.inject.Inject
+
+class GetCurrentContinueWatchingTvShowGenres @Inject constructor(
```
Comment (abdulazizacc) [inline domain/src/main/java/com/baghdad/domain/usecase/continueWatching/GetCurrentContinueWatchingTvShowGenres.kt:11]: here too

**Review by abdulazizacc — APPROVED** [review]
well done aboud

**Review by Hasa9nAli — APPROVED** [review]
