### PR TITLE
Fix/#243 image loader functionalities

### LINKED ISSUE #242: Fix image loader functionalities
- Fix the blurring accuracy applied to images.
- If there is a problem with image loading or caching performance using Coil, please try to improve it.
- Try to refactor the functionality using an object-oriented programming (OOP) approach.

### PR DESCRIPTION
**Pull request by MuhammedEdrees**
- Integrate nsfw detector model for detecting haram/unsafe images with much improved accuracy (~92.2%).
- Refactor blur logic to use a custom blur transformation that works with all different api levels and integrate it with coil `ImageRequest`.

https://github.com/user-attachments/assets/503129d6-43b5-4165-82e8-a464ea366059

### CODE REVIEW

File: design_system/src/main/java/com/baghdad/design_system/component/islamicImage/IslamicImage.kt [hunk 1]
```diff
@@ -0,0 +1,32 @@
+package com.baghdad.design_system.component.islamicImage
+
+import androidx.compose.runtime.Composable
+import androidx.compose.ui.Modifier
+import androidx.compose.ui.layout.ContentScale
+import com.baghdad.islamic_image_loader.ui.SafeImage
+
+@Composable
+fun IslamicImage(
```
Comment (ahmednasserzaza) [inline design_system/src/main/java/com/baghdad/design_system/component/islamicImage/IslamicImage.kt]: I think it would be better to move this function to a shared component within the UI module itself, so we can remove the dependency on the image loader module from the design system. The most important point I'd like to mention is regarding the image URL prefix, which is currently a static URL. We can define it here as a constant and prepend it to the image URLs. This way, we can avoid setting the image URL prefix each time in the mappers

File: islamic_image_loader/src/main/java/com/baghdad/islamic_image_loader/model/HaramImageDetector.kt [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+import android.graphics.Bitmap
+import com.baghdad.islamic_image_loader.ml.ModelNudeDetector
+import org.tensorflow.lite.DataType
+import org.tensorflow.lite.support.common.ops.NormalizeOp
+import org.tensorflow.lite.support.image.ImageProcessor
+import org.tensorflow.lite.support.image.TensorImage
+import org.tensorflow.lite.support.image.ops.ResizeOp
+import org.tensorflow.lite.support.tensorbuffer.TensorBuffer
+
+class HaramImageDetector(private val context: Context) {
```
Comment (ahmednasserzaza) [inline islamic_image_loader/src/main/java/com/baghdad/islamic_image_loader/model/HaramImageDetector.kt:13]: I liked that name 😅

**Review by ahmednasserzaza — DISMISSED** [review]
Awesome Work ❤️

**Review by fatmahgazy — APPROVED** [review]

**Review by MahmoodTarek — APPROVED** [review]

**Review by Arzo-zi — APPROVED** [review]
