### PR TITLE
Fix/#868 refresh saved list in home screen

### LINKED ISSUE #868: refresh saved list in home screen

### PR DESCRIPTION
**Pull request by omer1998**
### what has been done
- enable updating the home screen current state of saved list when the user add new list and return to the home screen
- enable updating the saved status of movie when the user save the movie in movie detail screen and return to the home screen  

https://github.com/user-attachments/assets/720c6c3b-1ab3-40dd-b5a9-9c2d55efdb0b

### CODE REVIEW

**Review by karrar-abbas — APPROVED** [review]

File: viewmodel/src/main/java/com/baghdad/viewmodel/home/HomeViewModel.kt [hunk 1]
```diff
@@ -74,13 +80,38 @@ constructor(
     private fun observeAppLanguage() {
         tryToCollect(
             flowProvider = { getAppLanguageUseCase.invoke() },
-            onNewValue = ::onLanguageChanged,
+            onNewValue = { onLanguageChanged() },
```
Comment (karrar-abbas) [inline viewmodel/src/main/java/com/baghdad/viewmodel/home/HomeViewModel.kt]: Why did you change it to lambda

File: viewmodel/src/main/java/com/baghdad/viewmodel/movieDetails/MovieDetailsViewModel.kt [hunk 2]
```diff
@@ -546,7 +547,9 @@ class MovieDetailsViewModel @Inject constructor(
     }
 
     private fun onGetMovieDetailsSuccess(details: SavedMovie) {
+        Log.i("movieDetails", "onGetMovieDetailsSuccess: ${details.isSaved}")
```
Comment (karrar-abbas) [inline viewmodel/src/main/java/com/baghdad/viewmodel/movieDetails/MovieDetailsViewModel.kt]: why you did not delete the log lines

**Review by karrar-abbas — DISMISSED** [review]
good work

**Review by abdulazizacc — DISMISSED** [review]

File: viewmodel/src/main/java/com/baghdad/viewmodel/home/HomeViewModel.kt (hunk 1 above)
Comment (omer1998) [reply viewmodel/src/main/java/com/baghdad/viewmodel/home/HomeViewModel.kt]: because i removed language parameter, so i removed reflection

**Review by ABDULLAHHG — DISMISSED** [review]

File: local_datasource/src/main/java/com/baghdad/localDatasource/roomDB/dao/SavedListMovieDao.kt [hunk 3]
```diff
@@ -29,4 +30,7 @@ interface SavedListMovieDao {
 
     @Query("DELETE FROM saved_list_movies")
     suspend fun deleteAllSavedMovies()
+
+    @Query("SELECT count(listId) FROM saved_list_movies") //movieId
+    fun getSavedMoviesCount(): Flow<Int>
```
Comment (Arzo-zi) [inline local_datasource/src/main/java/com/baghdad/localDatasource/roomDB/dao/SavedListMovieDao.kt:35]: you can delete the comment

**Review by Arzo-zi — DISMISSED** [review]

**Review by karrar-abbas — DISMISSED** [review]

**Review by ABDULLAHHG — APPROVED** [review]

**Review by Malak187 — APPROVED** [review]

**Review by FaresM0hamed — APPROVED** [review]
